### ISSUE TITLE
First interpolation of multiple in an attribute value is replaced with __DIFFHTML__

### ISSUE THREAD

**Issue by quarterto** [tbranyen/diffhtml#109]
e.g.:

```js
const foo = 'foo', bar = 'bar';
console.log(html`<span class="${foo}" />`);
//⇒ {nodeName: 'span', ..., attributes: [{name: 'class', value: 'foo'}]}
console.log(html`<span class="${foo} ${bar}" />`);
//⇒ {nodeName: 'span', ..., attributes: [{name: 'class', value: '__DIFFHTML__ bar'}]}
```

**Comment by tbranyen** [comment]
Woah that's certainly not good, I'll have a patch out shortly. Thanks for filing!

**Comment by tbranyen** [comment]
Hey @quarterto can you give this build a try: https://github.com/tbranyen/diffhtml/pull/110?

**Comment by tbranyen** [comment]
I realized the `isProp` regular expression wasn't running on the entire output, so only the first item would get "detected" as a prop. I've since fixed this with a smarter regex and running on the entire output instead of just the string preceding the interpolation.

Basically before it was testing: ` ` instead of `<span class="foo `
