### ISSUE TITLE
need benchmark .

### ISSUE THREAD

**Issue by leeluolee** [tbranyen/diffhtml#4]
I have tried a similiar test like diffhtml. But i find that performance is even worse than `innerHTML`. 

What about `diffhtml`

**Comment by tbranyen** [comment]
I know it sounds strange, but performance isn't a primary concern with this project.  As for benchmarks, check out http://vdom-benchmark.github.io/vdom-benchmark/

We're using virtual-dom internally atm, so you can assume relative performance.

**Comment by tbranyen** [comment]
Hey @leeluolee just wanted to apologize for the curt closing of this issue before.  I'm new to this space (virtual diff/rendering) and assumed that virtual-dom would be sufficient to benchmark against.  I brushed off your comment as "not my problem" because of the third party dependency.  However, I did some benchmarking and my experience was very similar to yours.  Basic rendering of a large dom was netting around 1fps... pathetic! So I created some benchmarks that you can see in the rewrite branch:

https://github.com/tbranyen/diffhtml/tree/rewrite/benchmarks

I've taken out virtual-dom as it is not suited for this module.  I've updated the codebase to use a webworker when available and calculate the diffing there.  It sends back an array of patches that are applied in a batch operation.  The performance is night and day!

Anyways, just wanted to let you know that performance is now at the forefront of my mind and I want to ensure stable diffing/patching w/ little performance overhead.
