### ISSUE TITLE
[Good First PR] HTML Entities encode/decode that works in Web Worker

### ISSUE THREAD

**Issue by tbranyen** [tbranyen/diffhtml#43]
Looking for a super minimal implementation that encode and decode HTML entities from a string. This should work in a Web Worker as well.

**Comment by jmeas** [comment]
I'd def look into existing modules for this. [This one](https://github.com/mdevils/node-html-entities), for instance, seems pretty lightweight and straightforward. A quick skim through the code didn't seem to show anything that wouldn't work in a web worker environment.

It'd suck to have an external dep, but the build system can just bundle it with diffhtml since it's unlikely that the user's app will be using that module as well.

**Comment by tbranyen** [comment]
That library is huge for our needs though, for instance: https://github.com/mdevils/node-html-entities/blob/master/lib/html5-entities.js#L1

We need a solution that is a single function, otherwise it's going to be very complex to embed into the Worker source: https://github.com/tbranyen/diffhtml/blob/master/lib/worker/create.js#L37-L82

**Comment by tbranyen** [comment]
This is becoming even more important. While benchmarking, the current method is getting hit way too hard. We need to be either always working with unencoded or encoded values and apply those to the DOM in a uniform way. As of right now I'm not sure, as it is not consistent.

Once we figure this out, the performance should be significantly improved for changing text (pretty much every benchmark).

**Comment by tbranyen** [comment]
I removed worker support and the new implementation only runs it when setting text.
