### ISSUE TITLE
[Question] Usage with template strings

### ISSUE THREAD

**Issue by shama** [tbranyen/diffhtml#55]
I've been thinking about the following way to create elements:

```js
function el (str) {
  var element = document.createElement('div')
  // ... Do some processing of the template first ...
  diff.outerHTML(element, str.raw[0])
  // ... customize/check the element before returning ...
  return element
}

module.exports = function (r) {
  return el`<svg viewBox="0 0 100 100">
    <circle cx="${r/2}" cy="${r/2}" r="${r}" />
  </svg>`
}

// ... later ...

var circle = require('./circle.js')(50)
document.body.appendChild(circle)
```

Which won't work because the `element` doesn't have a `parentNode`. So I'm about to try and parse out the outer element and then `diff.innerHTML(element, innerProcessedStuff)` instead. That way I can create elements and insert them later.

But I wanted to get your thoughts on this approach and any advice you might have using with template strings. Thanks for the awesome lib Tim!

**Comment by tbranyen** [comment]
So a big thing here is that you cannot change a specific DOM node to be a different type. I wish you could, because that'd make pooling much easier for me, but that means this will never be possible:

``` javascript
var div = document.createElement('div');
diff.outerHTML(div, `<svg></svg>`);
console.log(div); // how can we change this to now be an SVGElement?
```

So you'll always be restricted by that, the fact that it has no `parentNode` is probably some other error being hit or a more generic error message. We should improve the messaging here so that it's more obvious why it fails.

One question I have is why diffHTML for this particular use case? Would [html-tagged-template](https://github.com/straker/html-tagged-template) be more applicable to this use case? I'm not too sure what kind of diffing would be necessary if you're always creating a brand new element.

**Comment by shama** [comment]
Oh cool, I didn't know about `html-tagged-template`. I'll check that out!

My end goal is native-ish elements that can rerender themselves efficiently: https://github.com/shama/bel#data-down-events-up So they render first, an event occurs below that causes it to rerender using `diffhtml`.

I'm using [hyperscript](https://github.com/dominictarr/hyperscript) to build the initial element from a template string but it doesn't support svg nor lets me optionally inject unescaped html (among other things).

I may just end up rolling my own hyperscript or fallback to virtual-dom (it takes a little longer to render wanting a native element but it's doable).

I appreciate the answer, thanks!
