### ISSUE TITLE
Allow using buffers + extra thoughts

### ISSUE THREAD

**Issue by nfroidure** [tbranyen/diffhtml#7]
After having a look at React i also thought that something like an 'upsertHTML' would be far better and i'm really happy to see things moving that way.

One reason why i think the diffHTML approach is better is that building a string containing HTML and let browsers make the diff allows to avoid garbage collection cycles.

I think an optimal way to build that string would be to user buffers. Since the HTML contents of an application rarely vary in size, we could avoid garbage collection and have really impressive performances.

Another great thing with ArrayBuffers is that they are "transferable objects" https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers#Passing_data_by_transferring_ownership_(transferable_objects)

It means you can:
- compute the UI into a WebWorker and fill an ArrayBuffer with the new HTML
- transfer it to the main thread and render changes to the DOM.

Using 2 buffers, you could perform the HTML diff from the first while the next HTML to render would compute in the web worker to fill the second buffer. At each rendering cycle, you would just have to exchange buffers and render/compute again.

That's why i think diffHTML should accept array buffers containing encoded strings.

I assume you used virtual-dom to provide a quick implementation but i think that in the end, an HTML parser combined to a tree walker applying changes on the fly would be a better fit for implementing diffHTML.

Hope it helps.

**Comment by tbranyen** [comment]
Hey @nfroidure thanks so much for your thoughts here.  virtual-dom was definitely chosen to get things working for a quick implementation.  It worked for my needs so I didn't consider the performance too closely.  After creating a rudimentary benchmark, I found that it's not usable for large DOMs.  At least not with any level of performance ~150ms re-renders.

I've rewritten the diff to maintain a single virtual tree that is iterated and augmented with changes.  These changes are converted to patches which are then applied.  As for calculating the tree changes off the main thread, this is an excellent idea and I think the solution to even faster framerates.

**Comment by tbranyen** [comment]
Took your advice and now have diffing working in a web worker.  You simply pass a string to diffhtml, which it then converts to a u16array of codepoints.  A tree of the current DOM state is generated that links all present dom nodes to the internal node resolution.  The arraybuffer is transferred to the web worker, and tree is copied (only the first time though, and we can definitely inline this into the array buffeer and offset if that proves to be more performant).

All elements are resolved and created through an abstraction which will allow for dom pooling in the future.  It also enables passing around uuids instead of cyclic references.  The uuid is generated during the initial parsing of the DOM.

I had started on writing a loose html parser, but found will have to revisit with a better approach, because looping and breaking about the semantics is too complex.  I'm sure someone could write that, and I'd be grateful to adopt it, but realistically I need a tiny formal parser.  I'm currently using parse5, which is about 200k minified, way too large, but it works reliably for testing and has very low parse times for large doms (which is awesome).  The slowest part currently is the recursive formatting of the DOM tree produced by parse5.  Overall performance is fantastic for the user, zero lag or gc pauses.  Speed is very good, but processing is too high in the tight loop areas.

The focus is now:

- [ ] Finding (or writing) a more fitting html parser to only the properties we care about: (nodeName, nodeValue, attributes, childNodes),
- [ ] Improving tight loop performance.
- [ ] Tests asserting diff accuracy
- [ ] Supporting worker-less contexts (fall back to the same code w/o worker)
- [ ] Support fragments (currently only supports documentElement)
- [ ] Restore object/array pools and add primed dom pool (common elements like div, a, p, span, etc)

**Comment by tbranyen** [comment]
A potential candidate for the HTML parsing could be http://erik.eae.net/simplehtmlparser/simplehtmlparser.js, which implements a SAX interface.  This would allow us to grab only what we need and ignore the rest.  It's also incredibly small so it won't be a problem loading into the web worker.

**Comment by tbranyen** [comment]
Not sure if a DOM pool is really needed anymore.  We aren't creating excessive elements.  Going to punt on that for now.

**Comment by tbranyen** [comment]
Yup that html parser works much better.  Still rather slow, 100ms per loop for large pages, but overall went from 500ms per render to about 200ms.

**Comment by tbranyen** [comment]
The new html parser I'm using sits at around 80-100ms, but has more potential for optimization.  My goal is get sub 10ms parsing.  This will put us at:

Worker thread:

- 10ms parse
- 10ms diff
- 10ms emptying allocation pools

UI thread:

- 5ms patch (even with a ton of changes rarely goes about 5ms)

This will sit nicely at 35ms for total renders about 2.5x faster than it currently is on modern hardware.  Since the DOM operations operate on the main UI thread and are the fastest part of the render process, I'm focusing entirely on the Worker operations.

**Comment by nfroidure** [comment]
Wow! Didn't mind you would be that inspired by this issue!

I'll try to review your code and see if i can be of any help next week.

Feel free to give me some important information on particular things you'd like to get feedback.

**Comment by tbranyen** [comment]
@nfroidure at the moment it's proof-of-concept and I plan on refactoring heavily.  At the moment if you could look at:

https://github.com/tbranyen/diffhtml/blob/rewrite/lib/diff/patch_node.js#L176-L271

That's where the magic happens.   Check out how I'm creating and transferring the ArrayBuffer.  Maybe some ideas on faster HTML parsing?  I'm finding that the initial tree copying into the worker is really slow on large documents, I'm thinking maybe the initial virtual tree should be calculated in the worker as well.  Just ship over the uuids for the real elements.

**Comment by tbranyen** [comment]
Merged into master, still needs some performance and testing, but for now it's working good enough.  Thanks for all the help!

**Comment by nfroidure** [comment]
Unfortunately, i couldn't help that much... Great work btw!
