### ISSUE TITLE
`enableWorker` option does not seem to do anything

### ISSUE THREAD

**Issue by svapreddy** [tbranyen/diffhtml#81]
I am using `enableWorker: true` option as per the documentation. It looks like it is not doing anything. Or Am I using it in wrong way?

This is how I am using now:

`diff.innerHTML(this.element, div.innerHTML, {enableWorker: true})`

Thanks,
Prathap

**Comment by tbranyen** [comment]
Hey @svapreddy! Sorry the website is out of date, and I'm working on a new one. Please refer to the README for the documentation.

To answer your question, I removed Web Worker support since I wasn't able to get the performance and stability I wanted. Although with the new middleware tier I'm working on, I think I can change that by providing worker support as a middleware.

**Comment by svapreddy** [comment]
@tbranyen 👍 . And thanks for the great library.

**Comment by tbranyen** [comment]
Thank you! I have lots of good stuff coming
